[MODEL]
path = backpack.obj

[CONFIG]
; Process the model to convert quads and other polygons into triangles. This option does nothing with points and lines
triangulate = true
; Process the model to flip UV coordianes on Y axis. This option adjust material setting and bitangents accordingly
flip-uv = true
; Merge all nodes that have meshes without animations, bones, lights or cameras, reducing also the number of meshes. This is a huge performance boost.
; CAREFUL! Node hierarchy will be lost and loading times will be increased
optimize = true
; Calculate tangents and bitangents per vertex. This option won't do anything if model doesn't have normals
calculate-tangents = true
; Set to true to use sampled normals from normal map. Otherwise, primitive normal will be used
use-normal-map = true
; Set to true to use parallax mapping if a height map or displacement map is included in model
use-parallax-map = false

[TEXTURES]
tex_ao = ao_backpack.tex.ini

[DEBUG]
; Path to an external material that will be used for debugging purposes. 
; This material won't replace the original one, but will add another renderComponent to the GameObject
;debug-mat-path = Material_Debug.mat.ini

[MATERIAL]
void materialOverrides()
{
	// materialOverrides() function is meant to modify some aspect of original material() function, 
	// which in case of model loading, it's automatically generated based on model's internal date.
	// materialOverrides() is executed just after material() function in shaders

	diffuse = diffuse * pow(texture(tex_ao, input.uv), vec4(2.0));
	normal = height;
	height = vec4(0.0);
	ambient = ambient * diffuse;
}