[TEXTURE]
path = test_bricks_normal.jpg

[CONFIG]
; Wrap options: clamp, repeat, mirror
wrapU = repeat
wrapV = repeat
wrapW = repeat

; filter-min options: nearest, linear, nearest-nearestMip, linear-nearestMip, nearest-linearMip, linear-linearMip
; NOTE: any *Mip option will generate mipmaps automatically
filter-min = linear-linearMip

; filter-mag options: nearest, linear
filter-mag = linear
	
; If the texture is in sRGB, that is, the artist manually gamma corrected the colors working viewing a monitor, 
; setting to true re-correct sRGB to work in linear space
sRGB = false
	